server:
  port: 9001
spring:
  application:
    name: schools
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
